services:
  - type: web
    name: weather-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: API_KEY
        sync: false
